---
name: auto-terraform-apply-06-minimal-aws-terraform-bootstrap

permissions:
  id-token: write      # for fetching the OIDC token
  contents: read       # for actions/checkout

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 0" # only once a week!

jobs:
  tf-apply:
    runs-on: ubuntu-latest
    name: 06-minimal-aws-terraform-bootstrap - apply approved terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: master

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          role-session-name: GithubActionsTerraform
          aws-region: eu-west-1

      - name: Terraform apply
        uses: dflook/terraform-apply@82a1042d40c66856406bf648832fc5d6b03ca74c # v3
        with:
          path: examples/06-minimal-aws-terraform-bootstrap
          auto_approve: true

      - name: Terraform destroy
        uses: dflook/terraform-destroy@e800f4e75859cf422d7a1c6aa68480973ed55455 # v3
        with:
          path: examples/06-minimal-aws-terraform-bootstrap
