---
name: auto-terraform-apply-01-minimal-aws-cloudformation-bootstrap

permissions:
  id-token: write      # for fetching the OIDC token
  contents: read       # for actions/checkout
  pull-requests: write # For dflook comments on PR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  tf-apply:
    runs-on: ubuntu-latest
    name: 01-minimal-aws-cloudformation-bootstrap - apply approved terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          ref: master

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef # v2
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          role-session-name: GithubActionsTerraform
          aws-region: eu-west-1

      - name: Terraform apply
        uses: dflook/terraform-apply@3bbc265f1c260a7b38cebf10218a94e08285550a # v1
        with:
          path: examples/01-minimal-aws-cloudformation-bootstrap
          auto_approve: true
