---
name: auto-terraform-apply-01-minimal-aws-cloudformation-bootstrap

permissions:
  id-token: write      # for fetching the OIDC token
  contents: read       # for actions/checkout
  pull-requests: write # For dflook comments on PR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  tf-apply:
    runs-on: ubuntu-latest
    name: 01-minimal-aws-cloudformation-bootstrap - apply approved terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          ref: master

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          role-session-name: GithubActionsTerraform
          aws-region: eu-west-1

      - name: Terraform apply
        uses: dflook/terraform-apply@7a56cfb68f437341062f41afca87c71fc5b4bd5f # v1
        with:
          path: examples/01-minimal-aws-cloudformation-bootstrap
          auto_approve: true
