---
name: auto-terraform-apply-01-minimal-aws-cloudformation-bootstrap

permissions:
  id-token: write      # for fetching the OIDC token
  contents: read       # for actions/checkout
  pull-requests: write # For dflook comments on PR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  tf-apply:
    runs-on: ubuntu-latest
    name: 01-minimal-aws-cloudformation-bootstrap - apply approved terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
        with:
          ref: master

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # tag=v1
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          role-session-name: GithubActionsTerraform
          aws-region: eu-west-1

      - name: Terraform apply
        uses: dflook/terraform-apply@90c96554557e0821d6a6ee5579cbf305b788bb0e # tag=v1
        with:
          path: examples/01-minimal-aws-cloudformation-bootstrap
          auto_approve: true
