---
name: terraform-plan-02-minimal-gcp-tf-bootstrap

permissions:
  id-token: write      # for fetching the OIDC token
  contents: read       # for actions/checkout
  pull-requests: write # For dflook comments on PR

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "master"
    paths:
      - "examples/02-minimal-gcp-tf-bootstrap/**"
      - "modules/**"
      - ".github/workflows/**02.yaml"

jobs:
  tf-plan:
    runs-on: ubuntu-latest
    name: 02-minimal-gcp-tf-bootstrap - terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093' # v3
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: 'github-actions@pipetail-terraform.iam.gserviceaccount.com'

      - name: Terraform plan
        uses: dflook/terraform-plan@3f1559b085c5ceff68c3724c9b66c015a6c940cd # v3
        with:
          path: examples/02-minimal-gcp-tf-bootstrap
