---
name: terraform-plan-05-aws-complete

permissions:
  id-token: write      # for fetching the OIDC token
  contents: read       # for actions/checkout
  pull-requests: write # For dflook comments on PR

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "master"
    paths:
      - "examples/05-aws-complete/**"
      - ".github/workflows/**"

jobs:
  tf-plan:
    runs-on: ubuntu-latest
    name: 05-aws-complete - terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          role-session-name: GithubActionsTerraform
          aws-region: eu-west-1

      - name: Terraform plan
        uses: dflook/terraform-plan@3f1559b085c5ceff68c3724c9b66c015a6c940cd # v3
        with:
          path: examples/05-aws-complete
