---
name: terraform-prepare

permissions: read-all

on:
  pull_request:
    branches:
      - "master"

jobs:
  tf-fmt:
    runs-on: ubuntu-latest
    name: Check terraform file format
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Terraform fmt
        uses: dflook/terraform-fmt-check@1946c2a46d8d3a3001998f9c769a08cedcd28f5d # v3
        with:
          path: /
