---
name: terraform-apply-01-minimal-aws-cloudformation-bootstrap

permissions:
  id-token: write      # for fetching the OIDC token
  contents: read       # for actions/checkout
  pull-requests: write # For dflook comments on PR

on:
  push:
    branches:
      - "master"
    paths:
      - "examples/01-minimal-aws-cloudformation-bootstrap/**"
      - "modules/**"
      - ".github/workflows/**01.yaml"

jobs:
  tf-apply:
    runs-on: ubuntu-latest
    name: 01-minimal-aws-cloudformation-bootstrap - apply approved terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: master

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          role-session-name: GithubActionsTerraform
          aws-region: eu-west-1

      - name: Terraform apply
        uses: dflook/terraform-apply@61432ffb5b94226bdfc9cd68a1702a2c40e0db8b # v1
        with:
          path: examples/01-minimal-aws-cloudformation-bootstrap
